  - name: install glance (Ubuntu)
    apt:
      name: glance
      state: present
      update_cache: yes

  - name: start glance
    service:
       name: glance-api
       state: restarted
       enabled: yes

